# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20023_locations import InlineResponse20023Locations  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20023Locations(unittest.TestCase):
    """InlineResponse20023Locations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023Locations(self):
        """Test InlineResponse20023Locations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20023_locations.InlineResponse20023Locations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
