# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.allocation_inner_asset_class_short import AllocationInnerAssetClassShort  # noqa: E501
from swagger_client.rest import ApiException


class TestAllocationInnerAssetClassShort(unittest.TestCase):
    """AllocationInnerAssetClassShort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllocationInnerAssetClassShort(self):
        """Test AllocationInnerAssetClassShort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.allocation_inner_asset_class_short.AllocationInnerAssetClassShort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
