# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.trades_api import TradesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTradesApi(unittest.TestCase):
    """TradesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.trades_api.TradesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_iserver_account_trades_get(self):
        """Test case for iserver_account_trades_get

        List of Trades for the selected account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
