# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.contract_rules import ContractRules  # noqa: E501
from swagger_client.rest import ApiException


class TestContractRules(unittest.TestCase):
    """ContractRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContractRules(self):
        """Test ContractRules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.contract_rules.ContractRules()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
