# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AccountMaster(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'official_title': 'str'
    }

    attribute_map = {
        'title': 'title',
        'official_title': 'officialTitle'
    }

    def __init__(self, title=None, official_title=None):  # noqa: E501
        """AccountMaster - a model defined in Swagger"""  # noqa: E501

        self._title = None
        self._official_title = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if official_title is not None:
            self.official_title = official_title

    @property
    def title(self):
        """Gets the title of this AccountMaster.  # noqa: E501


        :return: The title of this AccountMaster.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this AccountMaster.


        :param title: The title of this AccountMaster.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def official_title(self):
        """Gets the official_title of this AccountMaster.  # noqa: E501


        :return: The official_title of this AccountMaster.  # noqa: E501
        :rtype: str
        """
        return self._official_title

    @official_title.setter
    def official_title(self, official_title):
        """Sets the official_title of this AccountMaster.


        :param official_title: The official_title of this AccountMaster.  # noqa: E501
        :type: str
        """

        self._official_title = official_title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountMaster, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountMaster):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
