# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SecdefInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conid': 'int',
        'name': 'str',
        'asset_class': 'str',
        'expiry': 'str',
        'last_trading_day': 'str',
        'group': 'str',
        'put_or_call': 'str',
        'sector': 'str',
        'sector_group': 'str',
        'strike': 'float',
        'ticker': 'str',
        'und_conid': 'int',
        'full_name': 'str',
        'page_size': 'int'
    }

    attribute_map = {
        'conid': 'conid',
        'name': 'name',
        'asset_class': 'assetClass',
        'expiry': 'expiry',
        'last_trading_day': 'lastTradingDay',
        'group': 'group',
        'put_or_call': 'putOrCall',
        'sector': 'sector',
        'sector_group': 'sectorGroup',
        'strike': 'strike',
        'ticker': 'ticker',
        'und_conid': 'undConid',
        'full_name': 'fullName',
        'page_size': 'pageSize'
    }

    def __init__(self, conid=None, name=None, asset_class=None, expiry=None, last_trading_day=None, group=None, put_or_call=None, sector=None, sector_group=None, strike=None, ticker=None, und_conid=None, full_name=None, page_size=None):  # noqa: E501
        """SecdefInner - a model defined in Swagger"""  # noqa: E501

        self._conid = None
        self._name = None
        self._asset_class = None
        self._expiry = None
        self._last_trading_day = None
        self._group = None
        self._put_or_call = None
        self._sector = None
        self._sector_group = None
        self._strike = None
        self._ticker = None
        self._und_conid = None
        self._full_name = None
        self._page_size = None
        self.discriminator = None

        if conid is not None:
            self.conid = conid
        if name is not None:
            self.name = name
        if asset_class is not None:
            self.asset_class = asset_class
        if expiry is not None:
            self.expiry = expiry
        if last_trading_day is not None:
            self.last_trading_day = last_trading_day
        if group is not None:
            self.group = group
        if put_or_call is not None:
            self.put_or_call = put_or_call
        if sector is not None:
            self.sector = sector
        if sector_group is not None:
            self.sector_group = sector_group
        if strike is not None:
            self.strike = strike
        if ticker is not None:
            self.ticker = ticker
        if und_conid is not None:
            self.und_conid = und_conid
        if full_name is not None:
            self.full_name = full_name
        if page_size is not None:
            self.page_size = page_size

    @property
    def conid(self):
        """Gets the conid of this SecdefInner.  # noqa: E501


        :return: The conid of this SecdefInner.  # noqa: E501
        :rtype: int
        """
        return self._conid

    @conid.setter
    def conid(self, conid):
        """Sets the conid of this SecdefInner.


        :param conid: The conid of this SecdefInner.  # noqa: E501
        :type: int
        """

        self._conid = conid

    @property
    def name(self):
        """Gets the name of this SecdefInner.  # noqa: E501


        :return: The name of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SecdefInner.


        :param name: The name of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def asset_class(self):
        """Gets the asset_class of this SecdefInner.  # noqa: E501


        :return: The asset_class of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._asset_class

    @asset_class.setter
    def asset_class(self, asset_class):
        """Sets the asset_class of this SecdefInner.


        :param asset_class: The asset_class of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._asset_class = asset_class

    @property
    def expiry(self):
        """Gets the expiry of this SecdefInner.  # noqa: E501


        :return: The expiry of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry):
        """Sets the expiry of this SecdefInner.


        :param expiry: The expiry of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._expiry = expiry

    @property
    def last_trading_day(self):
        """Gets the last_trading_day of this SecdefInner.  # noqa: E501


        :return: The last_trading_day of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._last_trading_day

    @last_trading_day.setter
    def last_trading_day(self, last_trading_day):
        """Sets the last_trading_day of this SecdefInner.


        :param last_trading_day: The last_trading_day of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._last_trading_day = last_trading_day

    @property
    def group(self):
        """Gets the group of this SecdefInner.  # noqa: E501


        :return: The group of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this SecdefInner.


        :param group: The group of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._group = group

    @property
    def put_or_call(self):
        """Gets the put_or_call of this SecdefInner.  # noqa: E501


        :return: The put_or_call of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._put_or_call

    @put_or_call.setter
    def put_or_call(self, put_or_call):
        """Sets the put_or_call of this SecdefInner.


        :param put_or_call: The put_or_call of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._put_or_call = put_or_call

    @property
    def sector(self):
        """Gets the sector of this SecdefInner.  # noqa: E501


        :return: The sector of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._sector

    @sector.setter
    def sector(self, sector):
        """Sets the sector of this SecdefInner.


        :param sector: The sector of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._sector = sector

    @property
    def sector_group(self):
        """Gets the sector_group of this SecdefInner.  # noqa: E501


        :return: The sector_group of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._sector_group

    @sector_group.setter
    def sector_group(self, sector_group):
        """Sets the sector_group of this SecdefInner.


        :param sector_group: The sector_group of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._sector_group = sector_group

    @property
    def strike(self):
        """Gets the strike of this SecdefInner.  # noqa: E501


        :return: The strike of this SecdefInner.  # noqa: E501
        :rtype: float
        """
        return self._strike

    @strike.setter
    def strike(self, strike):
        """Sets the strike of this SecdefInner.


        :param strike: The strike of this SecdefInner.  # noqa: E501
        :type: float
        """

        self._strike = strike

    @property
    def ticker(self):
        """Gets the ticker of this SecdefInner.  # noqa: E501


        :return: The ticker of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this SecdefInner.


        :param ticker: The ticker of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._ticker = ticker

    @property
    def und_conid(self):
        """Gets the und_conid of this SecdefInner.  # noqa: E501


        :return: The und_conid of this SecdefInner.  # noqa: E501
        :rtype: int
        """
        return self._und_conid

    @und_conid.setter
    def und_conid(self, und_conid):
        """Sets the und_conid of this SecdefInner.


        :param und_conid: The und_conid of this SecdefInner.  # noqa: E501
        :type: int
        """

        self._und_conid = und_conid

    @property
    def full_name(self):
        """Gets the full_name of this SecdefInner.  # noqa: E501


        :return: The full_name of this SecdefInner.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this SecdefInner.


        :param full_name: The full_name of this SecdefInner.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def page_size(self):
        """Gets the page_size of this SecdefInner.  # noqa: E501


        :return: The page_size of this SecdefInner.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this SecdefInner.


        :param page_size: The page_size of this SecdefInner.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SecdefInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecdefInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
