# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Account(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'account_id': 'str',
        'account_van': 'str',
        'account_title': 'str',
        'display_name': 'str',
        'account_alias': 'str',
        'account_status': 'float',
        'currency': 'str',
        'type': 'str',
        'trading_type': 'str',
        'faclient': 'bool',
        'parent': 'str',
        'desc': 'str',
        'covestor': 'bool',
        'master': 'AccountMaster'
    }

    attribute_map = {
        'id': 'id',
        'account_id': 'accountId',
        'account_van': 'accountVan',
        'account_title': 'accountTitle',
        'display_name': 'displayName',
        'account_alias': 'accountAlias',
        'account_status': 'accountStatus',
        'currency': 'currency',
        'type': 'type',
        'trading_type': 'tradingType',
        'faclient': 'faclient',
        'parent': 'parent',
        'desc': 'desc',
        'covestor': 'covestor',
        'master': 'master'
    }

    def __init__(self, id=None, account_id=None, account_van=None, account_title=None, display_name=None, account_alias=None, account_status=None, currency=None, type=None, trading_type=None, faclient=None, parent=None, desc=None, covestor=None, master=None):  # noqa: E501
        """Account - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._account_id = None
        self._account_van = None
        self._account_title = None
        self._display_name = None
        self._account_alias = None
        self._account_status = None
        self._currency = None
        self._type = None
        self._trading_type = None
        self._faclient = None
        self._parent = None
        self._desc = None
        self._covestor = None
        self._master = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if account_id is not None:
            self.account_id = account_id
        if account_van is not None:
            self.account_van = account_van
        if account_title is not None:
            self.account_title = account_title
        if display_name is not None:
            self.display_name = display_name
        if account_alias is not None:
            self.account_alias = account_alias
        if account_status is not None:
            self.account_status = account_status
        if currency is not None:
            self.currency = currency
        if type is not None:
            self.type = type
        if trading_type is not None:
            self.trading_type = trading_type
        if faclient is not None:
            self.faclient = faclient
        if parent is not None:
            self.parent = parent
        if desc is not None:
            self.desc = desc
        if covestor is not None:
            self.covestor = covestor
        if master is not None:
            self.master = master

    @property
    def id(self):
        """Gets the id of this Account.  # noqa: E501


        :return: The id of this Account.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Account.


        :param id: The id of this Account.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def account_id(self):
        """Gets the account_id of this Account.  # noqa: E501


        :return: The account_id of this Account.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this Account.


        :param account_id: The account_id of this Account.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def account_van(self):
        """Gets the account_van of this Account.  # noqa: E501


        :return: The account_van of this Account.  # noqa: E501
        :rtype: str
        """
        return self._account_van

    @account_van.setter
    def account_van(self, account_van):
        """Sets the account_van of this Account.


        :param account_van: The account_van of this Account.  # noqa: E501
        :type: str
        """

        self._account_van = account_van

    @property
    def account_title(self):
        """Gets the account_title of this Account.  # noqa: E501


        :return: The account_title of this Account.  # noqa: E501
        :rtype: str
        """
        return self._account_title

    @account_title.setter
    def account_title(self, account_title):
        """Sets the account_title of this Account.


        :param account_title: The account_title of this Account.  # noqa: E501
        :type: str
        """

        self._account_title = account_title

    @property
    def display_name(self):
        """Gets the display_name of this Account.  # noqa: E501


        :return: The display_name of this Account.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this Account.


        :param display_name: The display_name of this Account.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def account_alias(self):
        """Gets the account_alias of this Account.  # noqa: E501


        :return: The account_alias of this Account.  # noqa: E501
        :rtype: str
        """
        return self._account_alias

    @account_alias.setter
    def account_alias(self, account_alias):
        """Sets the account_alias of this Account.


        :param account_alias: The account_alias of this Account.  # noqa: E501
        :type: str
        """

        self._account_alias = account_alias

    @property
    def account_status(self):
        """Gets the account_status of this Account.  # noqa: E501


        :return: The account_status of this Account.  # noqa: E501
        :rtype: float
        """
        return self._account_status

    @account_status.setter
    def account_status(self, account_status):
        """Sets the account_status of this Account.


        :param account_status: The account_status of this Account.  # noqa: E501
        :type: float
        """

        self._account_status = account_status

    @property
    def currency(self):
        """Gets the currency of this Account.  # noqa: E501


        :return: The currency of this Account.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this Account.


        :param currency: The currency of this Account.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def type(self):
        """Gets the type of this Account.  # noqa: E501


        :return: The type of this Account.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Account.


        :param type: The type of this Account.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def trading_type(self):
        """Gets the trading_type of this Account.  # noqa: E501


        :return: The trading_type of this Account.  # noqa: E501
        :rtype: str
        """
        return self._trading_type

    @trading_type.setter
    def trading_type(self, trading_type):
        """Sets the trading_type of this Account.


        :param trading_type: The trading_type of this Account.  # noqa: E501
        :type: str
        """

        self._trading_type = trading_type

    @property
    def faclient(self):
        """Gets the faclient of this Account.  # noqa: E501


        :return: The faclient of this Account.  # noqa: E501
        :rtype: bool
        """
        return self._faclient

    @faclient.setter
    def faclient(self, faclient):
        """Sets the faclient of this Account.


        :param faclient: The faclient of this Account.  # noqa: E501
        :type: bool
        """

        self._faclient = faclient

    @property
    def parent(self):
        """Gets the parent of this Account.  # noqa: E501


        :return: The parent of this Account.  # noqa: E501
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this Account.


        :param parent: The parent of this Account.  # noqa: E501
        :type: str
        """

        self._parent = parent

    @property
    def desc(self):
        """Gets the desc of this Account.  # noqa: E501


        :return: The desc of this Account.  # noqa: E501
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc):
        """Sets the desc of this Account.


        :param desc: The desc of this Account.  # noqa: E501
        :type: str
        """

        self._desc = desc

    @property
    def covestor(self):
        """Gets the covestor of this Account.  # noqa: E501


        :return: The covestor of this Account.  # noqa: E501
        :rtype: bool
        """
        return self._covestor

    @covestor.setter
    def covestor(self, covestor):
        """Sets the covestor of this Account.


        :param covestor: The covestor of this Account.  # noqa: E501
        :type: bool
        """

        self._covestor = covestor

    @property
    def master(self):
        """Gets the master of this Account.  # noqa: E501


        :return: The master of this Account.  # noqa: E501
        :rtype: AccountMaster
        """
        return self._master

    @master.setter
    def master(self, master):
        """Sets the master of this Account.


        :param master: The master of this Account.  # noqa: E501
        :type: AccountMaster
        """

        self._master = master

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Account, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Account):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
