# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20018(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_31': 'str',
        '_55': 'str',
        '_58': 'str',
        '_70': 'str',
        '_71': 'str',
        '_72': 'str',
        '_73': 'str',
        '_74': 'str',
        '_75': 'str',
        '_76': 'str',
        '_77': 'str',
        '_78': 'str',
        '_82': 'str',
        '_83': 'str',
        '_84': 'str',
        '_85': 'str',
        '_86': 'str',
        '_87': 'str',
        '_88': 'str',
        '_6004': 'str',
        '_6008': 'str',
        '_6070': 'str',
        '_6072': 'str',
        '_6073': 'str',
        '_6119': 'str',
        '_6457': 'str',
        '_6509': 'str',
        '_7051': 'str',
        '_7059': 'str',
        '_7094': 'str',
        '_7219': 'str',
        '_7220': 'str',
        '_7221': 'str',
        '_7280': 'str',
        '_7281': 'str',
        '_7282': 'str',
        '_7284': 'str',
        '_7285': 'str',
        '_7286': 'str',
        '_7287': 'str',
        '_7288': 'str',
        '_7289': 'str',
        '_7290': 'str',
        '_7291': 'str',
        '_7292': 'str',
        '_7293': 'str',
        '_7294': 'str',
        '_7295': 'str',
        '_7296': 'str',
        '_7633': 'str',
        'server_id': 'str',
        'conid': 'int',
        'updated': 'int'
    }

    attribute_map = {
        '_31': '31',
        '_55': '55',
        '_58': '58',
        '_70': '70',
        '_71': '71',
        '_72': '72',
        '_73': '73',
        '_74': '74',
        '_75': '75',
        '_76': '76',
        '_77': '77',
        '_78': '78',
        '_82': '82',
        '_83': '83',
        '_84': '84',
        '_85': '85',
        '_86': '86',
        '_87': '87',
        '_88': '88',
        '_6004': '6004',
        '_6008': '6008',
        '_6070': '6070',
        '_6072': '6072',
        '_6073': '6073',
        '_6119': '6119',
        '_6457': '6457',
        '_6509': '6509',
        '_7051': '7051',
        '_7059': '7059',
        '_7094': '7094',
        '_7219': '7219',
        '_7220': '7220',
        '_7221': '7221',
        '_7280': '7280',
        '_7281': '7281',
        '_7282': '7282',
        '_7284': '7284',
        '_7285': '7285',
        '_7286': '7286',
        '_7287': '7287',
        '_7288': '7288',
        '_7289': '7289',
        '_7290': '7290',
        '_7291': '7291',
        '_7292': '7292',
        '_7293': '7293',
        '_7294': '7294',
        '_7295': '7295',
        '_7296': '7296',
        '_7633': '7633',
        'server_id': 'server_id',
        'conid': 'conid',
        'updated': '_updated'
    }

    def __init__(self, _31=None, _55=None, _58=None, _70=None, _71=None, _72=None, _73=None, _74=None, _75=None, _76=None, _77=None, _78=None, _82=None, _83=None, _84=None, _85=None, _86=None, _87=None, _88=None, _6004=None, _6008=None, _6070=None, _6072=None, _6073=None, _6119=None, _6457=None, _6509=None, _7051=None, _7059=None, _7094=None, _7219=None, _7220=None, _7221=None, _7280=None, _7281=None, _7282=None, _7284=None, _7285=None, _7286=None, _7287=None, _7288=None, _7289=None, _7290=None, _7291=None, _7292=None, _7293=None, _7294=None, _7295=None, _7296=None, _7633=None, server_id=None, conid=None, updated=None):  # noqa: E501
        """InlineResponse20018 - a model defined in Swagger"""  # noqa: E501

        self.__31 = None
        self.__55 = None
        self.__58 = None
        self.__70 = None
        self.__71 = None
        self.__72 = None
        self.__73 = None
        self.__74 = None
        self.__75 = None
        self.__76 = None
        self.__77 = None
        self.__78 = None
        self.__82 = None
        self.__83 = None
        self.__84 = None
        self.__85 = None
        self.__86 = None
        self.__87 = None
        self.__88 = None
        self.__6004 = None
        self.__6008 = None
        self.__6070 = None
        self.__6072 = None
        self.__6073 = None
        self.__6119 = None
        self.__6457 = None
        self.__6509 = None
        self.__7051 = None
        self.__7059 = None
        self.__7094 = None
        self.__7219 = None
        self.__7220 = None
        self.__7221 = None
        self.__7280 = None
        self.__7281 = None
        self.__7282 = None
        self.__7284 = None
        self.__7285 = None
        self.__7286 = None
        self.__7287 = None
        self.__7288 = None
        self.__7289 = None
        self.__7290 = None
        self.__7291 = None
        self.__7292 = None
        self.__7293 = None
        self.__7294 = None
        self.__7295 = None
        self.__7296 = None
        self.__7633 = None
        self._server_id = None
        self._conid = None
        self._updated = None
        self.discriminator = None

        if _31 is not None:
            self._31 = _31
        if _55 is not None:
            self._55 = _55
        if _58 is not None:
            self._58 = _58
        if _70 is not None:
            self._70 = _70
        if _71 is not None:
            self._71 = _71
        if _72 is not None:
            self._72 = _72
        if _73 is not None:
            self._73 = _73
        if _74 is not None:
            self._74 = _74
        if _75 is not None:
            self._75 = _75
        if _76 is not None:
            self._76 = _76
        if _77 is not None:
            self._77 = _77
        if _78 is not None:
            self._78 = _78
        if _82 is not None:
            self._82 = _82
        if _83 is not None:
            self._83 = _83
        if _84 is not None:
            self._84 = _84
        if _85 is not None:
            self._85 = _85
        if _86 is not None:
            self._86 = _86
        if _87 is not None:
            self._87 = _87
        if _88 is not None:
            self._88 = _88
        if _6004 is not None:
            self._6004 = _6004
        if _6008 is not None:
            self._6008 = _6008
        if _6070 is not None:
            self._6070 = _6070
        if _6072 is not None:
            self._6072 = _6072
        if _6073 is not None:
            self._6073 = _6073
        if _6119 is not None:
            self._6119 = _6119
        if _6457 is not None:
            self._6457 = _6457
        if _6509 is not None:
            self._6509 = _6509
        if _7051 is not None:
            self._7051 = _7051
        if _7059 is not None:
            self._7059 = _7059
        if _7094 is not None:
            self._7094 = _7094
        if _7219 is not None:
            self._7219 = _7219
        if _7220 is not None:
            self._7220 = _7220
        if _7221 is not None:
            self._7221 = _7221
        if _7280 is not None:
            self._7280 = _7280
        if _7281 is not None:
            self._7281 = _7281
        if _7282 is not None:
            self._7282 = _7282
        if _7284 is not None:
            self._7284 = _7284
        if _7285 is not None:
            self._7285 = _7285
        if _7286 is not None:
            self._7286 = _7286
        if _7287 is not None:
            self._7287 = _7287
        if _7288 is not None:
            self._7288 = _7288
        if _7289 is not None:
            self._7289 = _7289
        if _7290 is not None:
            self._7290 = _7290
        if _7291 is not None:
            self._7291 = _7291
        if _7292 is not None:
            self._7292 = _7292
        if _7293 is not None:
            self._7293 = _7293
        if _7294 is not None:
            self._7294 = _7294
        if _7295 is not None:
            self._7295 = _7295
        if _7296 is not None:
            self._7296 = _7296
        if _7633 is not None:
            self._7633 = _7633
        if server_id is not None:
            self.server_id = server_id
        if conid is not None:
            self.conid = conid
        if updated is not None:
            self.updated = updated

    @property
    def _31(self):
        """Gets the _31 of this InlineResponse20018.  # noqa: E501

        Last Price  # noqa: E501

        :return: The _31 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__31

    @_31.setter
    def _31(self, _31):
        """Sets the _31 of this InlineResponse20018.

        Last Price  # noqa: E501

        :param _31: The _31 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__31 = _31

    @property
    def _55(self):
        """Gets the _55 of this InlineResponse20018.  # noqa: E501

        Symbol  # noqa: E501

        :return: The _55 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__55

    @_55.setter
    def _55(self, _55):
        """Sets the _55 of this InlineResponse20018.

        Symbol  # noqa: E501

        :param _55: The _55 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__55 = _55

    @property
    def _58(self):
        """Gets the _58 of this InlineResponse20018.  # noqa: E501

        Text  # noqa: E501

        :return: The _58 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__58

    @_58.setter
    def _58(self, _58):
        """Sets the _58 of this InlineResponse20018.

        Text  # noqa: E501

        :param _58: The _58 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__58 = _58

    @property
    def _70(self):
        """Gets the _70 of this InlineResponse20018.  # noqa: E501

        High  # noqa: E501

        :return: The _70 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__70

    @_70.setter
    def _70(self, _70):
        """Sets the _70 of this InlineResponse20018.

        High  # noqa: E501

        :param _70: The _70 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__70 = _70

    @property
    def _71(self):
        """Gets the _71 of this InlineResponse20018.  # noqa: E501

        Low  # noqa: E501

        :return: The _71 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__71

    @_71.setter
    def _71(self, _71):
        """Sets the _71 of this InlineResponse20018.

        Low  # noqa: E501

        :param _71: The _71 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__71 = _71

    @property
    def _72(self):
        """Gets the _72 of this InlineResponse20018.  # noqa: E501

        Position  # noqa: E501

        :return: The _72 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__72

    @_72.setter
    def _72(self, _72):
        """Sets the _72 of this InlineResponse20018.

        Position  # noqa: E501

        :param _72: The _72 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__72 = _72

    @property
    def _73(self):
        """Gets the _73 of this InlineResponse20018.  # noqa: E501

        Market Value  # noqa: E501

        :return: The _73 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__73

    @_73.setter
    def _73(self, _73):
        """Sets the _73 of this InlineResponse20018.

        Market Value  # noqa: E501

        :param _73: The _73 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__73 = _73

    @property
    def _74(self):
        """Gets the _74 of this InlineResponse20018.  # noqa: E501

        Average Price  # noqa: E501

        :return: The _74 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__74

    @_74.setter
    def _74(self, _74):
        """Sets the _74 of this InlineResponse20018.

        Average Price  # noqa: E501

        :param _74: The _74 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__74 = _74

    @property
    def _75(self):
        """Gets the _75 of this InlineResponse20018.  # noqa: E501

        Unrealized PnL  # noqa: E501

        :return: The _75 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__75

    @_75.setter
    def _75(self, _75):
        """Sets the _75 of this InlineResponse20018.

        Unrealized PnL  # noqa: E501

        :param _75: The _75 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__75 = _75

    @property
    def _76(self):
        """Gets the _76 of this InlineResponse20018.  # noqa: E501

        Formatted position  # noqa: E501

        :return: The _76 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__76

    @_76.setter
    def _76(self, _76):
        """Sets the _76 of this InlineResponse20018.

        Formatted position  # noqa: E501

        :param _76: The _76 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__76 = _76

    @property
    def _77(self):
        """Gets the _77 of this InlineResponse20018.  # noqa: E501

        Formatted Unrealized PnL  # noqa: E501

        :return: The _77 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__77

    @_77.setter
    def _77(self, _77):
        """Sets the _77 of this InlineResponse20018.

        Formatted Unrealized PnL  # noqa: E501

        :param _77: The _77 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__77 = _77

    @property
    def _78(self):
        """Gets the _78 of this InlineResponse20018.  # noqa: E501

        Daily PnL  # noqa: E501

        :return: The _78 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__78

    @_78.setter
    def _78(self, _78):
        """Sets the _78 of this InlineResponse20018.

        Daily PnL  # noqa: E501

        :param _78: The _78 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__78 = _78

    @property
    def _82(self):
        """Gets the _82 of this InlineResponse20018.  # noqa: E501

        Change Price  # noqa: E501

        :return: The _82 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__82

    @_82.setter
    def _82(self, _82):
        """Sets the _82 of this InlineResponse20018.

        Change Price  # noqa: E501

        :param _82: The _82 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__82 = _82

    @property
    def _83(self):
        """Gets the _83 of this InlineResponse20018.  # noqa: E501

        Change Percent  # noqa: E501

        :return: The _83 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__83

    @_83.setter
    def _83(self, _83):
        """Sets the _83 of this InlineResponse20018.

        Change Percent  # noqa: E501

        :param _83: The _83 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__83 = _83

    @property
    def _84(self):
        """Gets the _84 of this InlineResponse20018.  # noqa: E501

        Bid Price  # noqa: E501

        :return: The _84 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__84

    @_84.setter
    def _84(self, _84):
        """Sets the _84 of this InlineResponse20018.

        Bid Price  # noqa: E501

        :param _84: The _84 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__84 = _84

    @property
    def _85(self):
        """Gets the _85 of this InlineResponse20018.  # noqa: E501

        Ask Size  # noqa: E501

        :return: The _85 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__85

    @_85.setter
    def _85(self, _85):
        """Sets the _85 of this InlineResponse20018.

        Ask Size  # noqa: E501

        :param _85: The _85 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__85 = _85

    @property
    def _86(self):
        """Gets the _86 of this InlineResponse20018.  # noqa: E501

        Ask Price  # noqa: E501

        :return: The _86 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__86

    @_86.setter
    def _86(self, _86):
        """Sets the _86 of this InlineResponse20018.

        Ask Price  # noqa: E501

        :param _86: The _86 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__86 = _86

    @property
    def _87(self):
        """Gets the _87 of this InlineResponse20018.  # noqa: E501

        Volume  # noqa: E501

        :return: The _87 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__87

    @_87.setter
    def _87(self, _87):
        """Sets the _87 of this InlineResponse20018.

        Volume  # noqa: E501

        :param _87: The _87 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__87 = _87

    @property
    def _88(self):
        """Gets the _88 of this InlineResponse20018.  # noqa: E501

        Bid Size  # noqa: E501

        :return: The _88 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__88

    @_88.setter
    def _88(self, _88):
        """Sets the _88 of this InlineResponse20018.

        Bid Size  # noqa: E501

        :param _88: The _88 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__88 = _88

    @property
    def _6004(self):
        """Gets the _6004 of this InlineResponse20018.  # noqa: E501

        Exchange  # noqa: E501

        :return: The _6004 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6004

    @_6004.setter
    def _6004(self, _6004):
        """Sets the _6004 of this InlineResponse20018.

        Exchange  # noqa: E501

        :param _6004: The _6004 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6004 = _6004

    @property
    def _6008(self):
        """Gets the _6008 of this InlineResponse20018.  # noqa: E501

        Conid  # noqa: E501

        :return: The _6008 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6008

    @_6008.setter
    def _6008(self, _6008):
        """Sets the _6008 of this InlineResponse20018.

        Conid  # noqa: E501

        :param _6008: The _6008 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6008 = _6008

    @property
    def _6070(self):
        """Gets the _6070 of this InlineResponse20018.  # noqa: E501

        Security Type  # noqa: E501

        :return: The _6070 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6070

    @_6070.setter
    def _6070(self, _6070):
        """Sets the _6070 of this InlineResponse20018.

        Security Type  # noqa: E501

        :param _6070: The _6070 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6070 = _6070

    @property
    def _6072(self):
        """Gets the _6072 of this InlineResponse20018.  # noqa: E501

        Months  # noqa: E501

        :return: The _6072 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6072

    @_6072.setter
    def _6072(self, _6072):
        """Sets the _6072 of this InlineResponse20018.

        Months  # noqa: E501

        :param _6072: The _6072 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6072 = _6072

    @property
    def _6073(self):
        """Gets the _6073 of this InlineResponse20018.  # noqa: E501

        Regular Expiry  # noqa: E501

        :return: The _6073 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6073

    @_6073.setter
    def _6073(self, _6073):
        """Sets the _6073 of this InlineResponse20018.

        Regular Expiry  # noqa: E501

        :param _6073: The _6073 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6073 = _6073

    @property
    def _6119(self):
        """Gets the _6119 of this InlineResponse20018.  # noqa: E501

        Marker for market data delivery method (similar to request id)  # noqa: E501

        :return: The _6119 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6119

    @_6119.setter
    def _6119(self, _6119):
        """Sets the _6119 of this InlineResponse20018.

        Marker for market data delivery method (similar to request id)  # noqa: E501

        :param _6119: The _6119 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6119 = _6119

    @property
    def _6457(self):
        """Gets the _6457 of this InlineResponse20018.  # noqa: E501

        Underlying Conid. Use /trsrv/secdef to get more information about the security  # noqa: E501

        :return: The _6457 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6457

    @_6457.setter
    def _6457(self, _6457):
        """Sets the _6457 of this InlineResponse20018.

        Underlying Conid. Use /trsrv/secdef to get more information about the security  # noqa: E501

        :param _6457: The _6457 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6457 = _6457

    @property
    def _6509(self):
        """Gets the _6509 of this InlineResponse20018.  # noqa: E501

        Market Data Availability. The field may contain two chars. The first char is the primary code: R = Realtime, D = Delayed, Z = Frozen, Y = Frozen Delayed. The second char is the secondary code: P = Snapshot Available, p = Consolidated.   # noqa: E501

        :return: The _6509 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__6509

    @_6509.setter
    def _6509(self, _6509):
        """Sets the _6509 of this InlineResponse20018.

        Market Data Availability. The field may contain two chars. The first char is the primary code: R = Realtime, D = Delayed, Z = Frozen, Y = Frozen Delayed. The second char is the secondary code: P = Snapshot Available, p = Consolidated.   # noqa: E501

        :param _6509: The _6509 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__6509 = _6509

    @property
    def _7051(self):
        """Gets the _7051 of this InlineResponse20018.  # noqa: E501

        Company name  # noqa: E501

        :return: The _7051 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7051

    @_7051.setter
    def _7051(self, _7051):
        """Sets the _7051 of this InlineResponse20018.

        Company name  # noqa: E501

        :param _7051: The _7051 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7051 = _7051

    @property
    def _7059(self):
        """Gets the _7059 of this InlineResponse20018.  # noqa: E501

        Last Size  # noqa: E501

        :return: The _7059 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7059

    @_7059.setter
    def _7059(self, _7059):
        """Sets the _7059 of this InlineResponse20018.

        Last Size  # noqa: E501

        :param _7059: The _7059 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7059 = _7059

    @property
    def _7094(self):
        """Gets the _7094 of this InlineResponse20018.  # noqa: E501

        Conid + Exchange  # noqa: E501

        :return: The _7094 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7094

    @_7094.setter
    def _7094(self, _7094):
        """Sets the _7094 of this InlineResponse20018.

        Conid + Exchange  # noqa: E501

        :param _7094: The _7094 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7094 = _7094

    @property
    def _7219(self):
        """Gets the _7219 of this InlineResponse20018.  # noqa: E501

        Contract Description  # noqa: E501

        :return: The _7219 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7219

    @_7219.setter
    def _7219(self, _7219):
        """Sets the _7219 of this InlineResponse20018.

        Contract Description  # noqa: E501

        :param _7219: The _7219 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7219 = _7219

    @property
    def _7220(self):
        """Gets the _7220 of this InlineResponse20018.  # noqa: E501

        Contract Description  # noqa: E501

        :return: The _7220 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7220

    @_7220.setter
    def _7220(self, _7220):
        """Sets the _7220 of this InlineResponse20018.

        Contract Description  # noqa: E501

        :param _7220: The _7220 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7220 = _7220

    @property
    def _7221(self):
        """Gets the _7221 of this InlineResponse20018.  # noqa: E501

        Listing Exchange  # noqa: E501

        :return: The _7221 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7221

    @_7221.setter
    def _7221(self, _7221):
        """Sets the _7221 of this InlineResponse20018.

        Listing Exchange  # noqa: E501

        :param _7221: The _7221 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7221 = _7221

    @property
    def _7280(self):
        """Gets the _7280 of this InlineResponse20018.  # noqa: E501

        Industry  # noqa: E501

        :return: The _7280 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7280

    @_7280.setter
    def _7280(self, _7280):
        """Sets the _7280 of this InlineResponse20018.

        Industry  # noqa: E501

        :param _7280: The _7280 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7280 = _7280

    @property
    def _7281(self):
        """Gets the _7281 of this InlineResponse20018.  # noqa: E501

        Category  # noqa: E501

        :return: The _7281 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7281

    @_7281.setter
    def _7281(self, _7281):
        """Sets the _7281 of this InlineResponse20018.

        Category  # noqa: E501

        :param _7281: The _7281 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7281 = _7281

    @property
    def _7282(self):
        """Gets the _7282 of this InlineResponse20018.  # noqa: E501

        Average Daily Volume  # noqa: E501

        :return: The _7282 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7282

    @_7282.setter
    def _7282(self, _7282):
        """Sets the _7282 of this InlineResponse20018.

        Average Daily Volume  # noqa: E501

        :param _7282: The _7282 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7282 = _7282

    @property
    def _7284(self):
        """Gets the _7284 of this InlineResponse20018.  # noqa: E501

        Historic Volume (30d)  # noqa: E501

        :return: The _7284 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7284

    @_7284.setter
    def _7284(self, _7284):
        """Sets the _7284 of this InlineResponse20018.

        Historic Volume (30d)  # noqa: E501

        :param _7284: The _7284 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7284 = _7284

    @property
    def _7285(self):
        """Gets the _7285 of this InlineResponse20018.  # noqa: E501

        Put/Call Ratio  # noqa: E501

        :return: The _7285 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7285

    @_7285.setter
    def _7285(self, _7285):
        """Sets the _7285 of this InlineResponse20018.

        Put/Call Ratio  # noqa: E501

        :param _7285: The _7285 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7285 = _7285

    @property
    def _7286(self):
        """Gets the _7286 of this InlineResponse20018.  # noqa: E501

        Dividend Amount  # noqa: E501

        :return: The _7286 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7286

    @_7286.setter
    def _7286(self, _7286):
        """Sets the _7286 of this InlineResponse20018.

        Dividend Amount  # noqa: E501

        :param _7286: The _7286 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7286 = _7286

    @property
    def _7287(self):
        """Gets the _7287 of this InlineResponse20018.  # noqa: E501

        Dividend Yield %  # noqa: E501

        :return: The _7287 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7287

    @_7287.setter
    def _7287(self, _7287):
        """Sets the _7287 of this InlineResponse20018.

        Dividend Yield %  # noqa: E501

        :param _7287: The _7287 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7287 = _7287

    @property
    def _7288(self):
        """Gets the _7288 of this InlineResponse20018.  # noqa: E501

        Ex-date of the dividend  # noqa: E501

        :return: The _7288 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7288

    @_7288.setter
    def _7288(self, _7288):
        """Sets the _7288 of this InlineResponse20018.

        Ex-date of the dividend  # noqa: E501

        :param _7288: The _7288 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7288 = _7288

    @property
    def _7289(self):
        """Gets the _7289 of this InlineResponse20018.  # noqa: E501

        Market Cap  # noqa: E501

        :return: The _7289 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7289

    @_7289.setter
    def _7289(self, _7289):
        """Sets the _7289 of this InlineResponse20018.

        Market Cap  # noqa: E501

        :param _7289: The _7289 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7289 = _7289

    @property
    def _7290(self):
        """Gets the _7290 of this InlineResponse20018.  # noqa: E501

        P/E  # noqa: E501

        :return: The _7290 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7290

    @_7290.setter
    def _7290(self, _7290):
        """Sets the _7290 of this InlineResponse20018.

        P/E  # noqa: E501

        :param _7290: The _7290 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7290 = _7290

    @property
    def _7291(self):
        """Gets the _7291 of this InlineResponse20018.  # noqa: E501

        EPS  # noqa: E501

        :return: The _7291 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7291

    @_7291.setter
    def _7291(self, _7291):
        """Sets the _7291 of this InlineResponse20018.

        EPS  # noqa: E501

        :param _7291: The _7291 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7291 = _7291

    @property
    def _7292(self):
        """Gets the _7292 of this InlineResponse20018.  # noqa: E501

        Cost Basis  # noqa: E501

        :return: The _7292 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7292

    @_7292.setter
    def _7292(self, _7292):
        """Sets the _7292 of this InlineResponse20018.

        Cost Basis  # noqa: E501

        :param _7292: The _7292 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7292 = _7292

    @property
    def _7293(self):
        """Gets the _7293 of this InlineResponse20018.  # noqa: E501

        52 Week High  # noqa: E501

        :return: The _7293 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7293

    @_7293.setter
    def _7293(self, _7293):
        """Sets the _7293 of this InlineResponse20018.

        52 Week High  # noqa: E501

        :param _7293: The _7293 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7293 = _7293

    @property
    def _7294(self):
        """Gets the _7294 of this InlineResponse20018.  # noqa: E501

        52 Week Low  # noqa: E501

        :return: The _7294 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7294

    @_7294.setter
    def _7294(self, _7294):
        """Sets the _7294 of this InlineResponse20018.

        52 Week Low  # noqa: E501

        :param _7294: The _7294 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7294 = _7294

    @property
    def _7295(self):
        """Gets the _7295 of this InlineResponse20018.  # noqa: E501

        Open Price  # noqa: E501

        :return: The _7295 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7295

    @_7295.setter
    def _7295(self, _7295):
        """Sets the _7295 of this InlineResponse20018.

        Open Price  # noqa: E501

        :param _7295: The _7295 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7295 = _7295

    @property
    def _7296(self):
        """Gets the _7296 of this InlineResponse20018.  # noqa: E501

        Close Price  # noqa: E501

        :return: The _7296 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7296

    @_7296.setter
    def _7296(self, _7296):
        """Sets the _7296 of this InlineResponse20018.

        Close Price  # noqa: E501

        :param _7296: The _7296 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7296 = _7296

    @property
    def _7633(self):
        """Gets the _7633 of this InlineResponse20018.  # noqa: E501

        Implied volatility of the option  # noqa: E501

        :return: The _7633 of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self.__7633

    @_7633.setter
    def _7633(self, _7633):
        """Sets the _7633 of this InlineResponse20018.

        Implied volatility of the option  # noqa: E501

        :param _7633: The _7633 of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self.__7633 = _7633

    @property
    def server_id(self):
        """Gets the server_id of this InlineResponse20018.  # noqa: E501


        :return: The server_id of this InlineResponse20018.  # noqa: E501
        :rtype: str
        """
        return self._server_id

    @server_id.setter
    def server_id(self, server_id):
        """Sets the server_id of this InlineResponse20018.


        :param server_id: The server_id of this InlineResponse20018.  # noqa: E501
        :type: str
        """

        self._server_id = server_id

    @property
    def conid(self):
        """Gets the conid of this InlineResponse20018.  # noqa: E501


        :return: The conid of this InlineResponse20018.  # noqa: E501
        :rtype: int
        """
        return self._conid

    @conid.setter
    def conid(self, conid):
        """Sets the conid of this InlineResponse20018.


        :param conid: The conid of this InlineResponse20018.  # noqa: E501
        :type: int
        """

        self._conid = conid

    @property
    def updated(self):
        """Gets the updated of this InlineResponse20018.  # noqa: E501


        :return: The updated of this InlineResponse20018.  # noqa: E501
        :rtype: int
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this InlineResponse20018.


        :param updated: The updated of this InlineResponse20018.  # noqa: E501
        :type: int
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20018, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20018):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
