# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StocksInnerContracts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conid': 'int',
        'exchange': 'str'
    }

    attribute_map = {
        'conid': 'conid',
        'exchange': 'exchange'
    }

    def __init__(self, conid=None, exchange=None):  # noqa: E501
        """StocksInnerContracts - a model defined in Swagger"""  # noqa: E501

        self._conid = None
        self._exchange = None
        self.discriminator = None

        if conid is not None:
            self.conid = conid
        if exchange is not None:
            self.exchange = exchange

    @property
    def conid(self):
        """Gets the conid of this StocksInnerContracts.  # noqa: E501

        conid of the stock contract  # noqa: E501

        :return: The conid of this StocksInnerContracts.  # noqa: E501
        :rtype: int
        """
        return self._conid

    @conid.setter
    def conid(self, conid):
        """Sets the conid of this StocksInnerContracts.

        conid of the stock contract  # noqa: E501

        :param conid: The conid of this StocksInnerContracts.  # noqa: E501
        :type: int
        """

        self._conid = conid

    @property
    def exchange(self):
        """Gets the exchange of this StocksInnerContracts.  # noqa: E501


        :return: The exchange of this StocksInnerContracts.  # noqa: E501
        :rtype: str
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this StocksInnerContracts.


        :param exchange: The exchange of this StocksInnerContracts.  # noqa: E501
        :type: str
        """

        self._exchange = exchange

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StocksInnerContracts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StocksInnerContracts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
