# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.performance_tpps import PerformanceTpps  # noqa: E501
from swagger_client.rest import ApiException


class TestPerformanceTpps(unittest.TestCase):
    """PerformanceTpps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerformanceTpps(self):
        """Test PerformanceTpps"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.performance_tpps.PerformanceTpps()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
