# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inds_inner import IndsInner  # noqa: E501
from swagger_client.rest import ApiException


class TestIndsInner(unittest.TestCase):
    """IndsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndsInner(self):
        """Test IndsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inds_inner.IndsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
