# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.portfolio_analyst_api import PortfolioAnalystApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPortfolioAnalystApi(unittest.TestCase):
    """PortfolioAnalystApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.portfolio_analyst_api.PortfolioAnalystApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pa_performance_post(self):
        """Test case for pa_performance_post

        Account Performance  # noqa: E501
        """
        pass

    def test_pa_summary_post(self):
        """Test case for pa_summary_post

        Account Balance's Summary  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
