# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20023_location_tree import InlineResponse20023LocationTree  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20023LocationTree(unittest.TestCase):
    """InlineResponse20023LocationTree unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023LocationTree(self):
        """Test InlineResponse20023LocationTree"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20023_location_tree.InlineResponse20023LocationTree()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
