# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scanner_api import ScannerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScannerApi(unittest.TestCase):
    """ScannerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.scanner_api.ScannerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_iserver_scanner_params_get(self):
        """Test case for iserver_scanner_params_get

        get lists of available scanners  # noqa: E501
        """
        pass

    def test_iserver_scanner_run_post(self):
        """Test case for iserver_scanner_run_post

        run scanner to get a list of contracts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
